version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: sgt-mysql-container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Dev@1234
      MYSQL_DATABASE: sgt
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: Dev@1234
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: ./sgt-backend
    container_name: sgt-backend-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://sgt-mysql-container:3306/sgt
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Dev@1234
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    build:
      context: ./sgt-frontend
    container_name: sgt-frontend-container
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:

volumes:
  mysql-data:
